// Generated by CoffeeScript 1.9.3
(function() {
  var app, region;

  console.log('loaded bro');

  app = new Mn.Application();

  app.on('start', function() {
    Backbone.history.start();
    return console.log('started');
  });

  app.start();

  region = new Backbone.Marionette.Region({
    el: '#content'
  });

  app.addRegions({
    content: '#content'
  });

  $.getJSON("http://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/significant_month.geojson", function(data) {
    return console.log(data['features']);
  });

}).call(this);
